version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    container_name: app_postgres_db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - app_net
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - app_net
    depends_on:
      - db

  template_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    container_name: template_app
    volumes:
      - .:/template
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_net
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - db

networks:
  app_net:
    external: true

volumes:
  postgres_data: